const snkprem = () => { 
  return `
  *「 RULES FOR PREMIUM USER!!! 」*
1. DILARANG TELFON BOT!!
2. DILARANG SPAM BOT
3. DILARANG MENGGUNAKAN FITUR BOT SEENAKNYA
4. DILARANG SPAM VIRTEX
5. DILARANG MENJUAL BOT
6. DILARANG MEMASUKKAN BOT LEBIH DARI 2 GC
7. DILARANG SPAM OWNER JIKA INGIN MEMPERPANJANG MASA AKTIF PREMIUMNYA 
8. JAGA ETIKA DAN KESOPANAN

JIKA MELANGGAR AKAN DICABUT LICENSI PREMIUMNYA!!!`
}
exports.snkprem = snkprem